# Generated by Django 3.1.6 on 2021-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
